# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HYSgfcQ9BFPqIscFzGvzGZKwcDniS7u3
"""

from google.colab import drive
drive.mount('/content/drive')

import matplotlib.pyplot as plt 
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/ReplicatedAcousticFeatures-ParkinsonDatabase.csv')

from sklearn.preprocessing import LabelEncoder
lb_make = LabelEncoder()
df['ID'] = lb_make.fit_transform(df['ID'])

df.head()

df.corr()

X = df.iloc[:, :-1]
Y = df.iloc[:, -1:]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state = 42)

sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p=2)
clf.fit(X_train,y_train)

from sklearn.metrics import accuracy_score, precision_score, precision_score, precision_recall_fscore_support

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print('K Neighbor')
print('Accuracy = ' + str(acc))
mae_lr = round(metrics.mean_absolute_error(y_test, y_pred), 4) 
mse_lr = round(metrics.mean_squared_error(y_test, y_pred), 4) 
print('MAE = ' +str(mae_lr))
print('MSE = ' +str(mse_lr))
rslt = precision_recall_fscore_support(y_test, y_pred, average=None,labels=[1, 2])

